In [1]:
from numpy import *
a = arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [18]:
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))

(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [22]:
b=array([6,7,8])
print(b)
print(type(b))

[6 7 8]
<class 'numpy.ndarray'>


In [23]:
a=array([1,2,3])
print(a.dtype)

int64


In [29]:
b=array([8.1,9.1, 9.7])
print(b.dtype)

float64


In [34]:
# a=array(1,2,3)
a=array([1,2,3])
a

array([1, 2, 3])

In [40]:
a1 = a
a2 = array([[1,2], [2,3]])
a3 = array([[[1,2], [2,3]], [[3,4], [4,5]]], dtype=float)


print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2]
 [2 3]]
[[[1. 2.]
  [2. 3.]]

 [[3. 4.]
  [4. 5.]]]


In [53]:
zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
ones((2,3,4), dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [84]:
empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
arange(10,31,5)

array([10, 15, 20, 25, 30])

In [91]:
arange(0.2,1.4,0.1)

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3])

In [99]:
linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [105]:
a=array([[1],[2],[3]])
b=array([[4,5,6]])
a*b
dot(b,a)

array([[32]])

In [107]:
a=array([1,2,3])
b=array([4,5,6])
a*b
dot(b,a)

32

In [66]:
a=array([1,2,3])
b=array([4,5,6])
a+b

array([5, 7, 9])

In [114]:
a=array([1,2,3])
sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [122]:
a=array([[1],[2],[3]])
a.max()

3

In [124]:
c = array([[1,2,3],
           [4,5,5],
           [6,7,7]
          ])
c.sum(axis=0)

array([11, 14, 15])

In [128]:
c = array([[1,2,3],
           [4,5,5],
           [6,7,7]
          ])
c.sum(axis=1)

array([ 6, 14, 20])

In [130]:
c = array([[1,2,3],
           [4,5,5],
           [6,7,7]
          ])
c.min(axis=1)

array([1, 4, 6])

In [134]:
c = array([[1,2,3],
           [4,5,5],
           [6,7,7]
          ])
c.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  8],
       [11, 14, 15]])

In [139]:
a=arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [138]:
a[2:5]

array([ 8, 27, 64])

In [144]:
a[:10:3] #0-10 take every 3rd element

array([  0,  27, 216, 729])

In [160]:
a[2:5:-1]

array([], dtype=int64)

In [165]:
def f(x,y,z):
    return 2+x+y

d=fromfunction(f, (4,5,6), dtype=int64)
d

array([[[2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6]],

       [[3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7]],

       [[4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8]],

       [[5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9]]])

In [166]:
d[-1]

array([[5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9]])

In [171]:
print(d.flat)
for element in d.flat:
    print(element)

2
2
2
2
2
2
3
3
3
3
3
3
4
4
4
4
4
4
5
5
5
5
5
5
6
6
6
6
6
6
3
3
3
3
3
3
4
4
4
4
4
4
5
5
5
5
5
5
6
6
6
6
6
6
7
7
7
7
7
7
4
4
4
4
4
4
5
5
5
5
5
5
6
6
6
6
6
6
7
7
7
7
7
7
8
8
8
8
8
8
5
5
5
5
5
5
6
6
6
6
6
6
7
7
7
7
7
7
8
8
8
8
8
8
9
9
9
9
9
9


In [3]:
d.ravel()

NameError: name 'd' is not defined

In [36]:
a = floor(10*random.random((3,4)))
a.shape
print(a.ravel())

print("\n6*2 array\n")

a.shape = (6,2)
print(a)


print("\n2*3*2 array\n")
a.resize((2,3,2))

print(a)

[2. 2. 9. 4. 7. 6. 4. 5. 6. 7. 1. 4.]

6*2 array

[[2. 2.]
 [9. 4.]
 [7. 6.]
 [4. 5.]
 [6. 7.]
 [1. 4.]]

2*3*2 array

[[[2. 2.]
  [9. 4.]
  [7. 6.]]

 [[4. 5.]
  [6. 7.]
  [1. 4.]]]


In [39]:
a = floor(10*random.random((3,4)))
a.reshape(3,-1)

array([[2., 2., 4., 5.],
       [4., 6., 5., 8.],
       [8., 3., 4., 5.]])

In [61]:
a = floor(10*random.random((2,12)))
hsplit(a,12)

[array([[2.],
        [5.]]), array([[5.],
        [8.]]), array([[9.],
        [8.]]), array([[9.],
        [3.]]), array([[5.],
        [8.]]), array([[4.],
        [3.]]), array([[2.],
        [9.]]), array([[4.],
        [9.]]), array([[3.],
        [9.]]), array([[5.],
        [5.]]), array([[8.],
        [7.]]), array([[9.],
        [0.]])]

In [54]:
c=a
c is a

True

In [99]:
d=a.view
d is a

False

In [101]:
e=a.copy
e is a

AttributeError: 'builtin_function_or_method' object has no attribute 'base'

In [88]:
def f(x,y):
       return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
print(b)
b[0:5,3]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([ 3, 13, 23, 33, 43])

In [94]:
b[:,0]

array([ 0, 10, 20, 30, 40])

In [109]:
b[:,1:2]

array([[ 1],
       [11],
       [21],
       [31],
       [41]])

In [98]:
b[-1]

array([40, 41, 42, 43])

In [180]:
a=array([[1,2,3],[7,92,2]])
print(a.shape)
a[::-1,::-1]

(2, 3)


array([[ 2, 92,  7],
       [ 3,  2,  1]])

In [182]:
# Reversing an array
a=array([1,2,3])
print(a[::-1])


[3 2 1]


In [196]:
a=[1,2,3]
b=[3,4,5]
c=[6,7,8]
ax,bx,cx = ix_(a,b,c)
print(ax.shape, bx.shape, cs.shape)

print("ax", ax)
print("bx", bx)
print("cx", cx)

(3, 1, 1) (1, 3, 1) (1, 1, 3)
ax [[[1]]

 [[2]]

 [[3]]]
bx [[[3]
  [4]
  [5]]]
cx [[[6 7 8]]]


In [202]:
a = array([[1.0, 2.0], [3.0, 4.0]])
j = array([[0.0, -1.0], [1.0, 0.0]])

a.transpose()

dot(a,j)

array([[ 2., -1.],
       [ 4., -3.]])

In [206]:
from numpy.linalg import *
eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [208]:
y = array([[5.], [7.]])
solve(a,y)

array([[-3.],
       [ 4.]])

In [220]:
x = arange(0,10,2)                     # x=([0,2,4,6,8])
y = arange(5)                          # y=([0,1,2,3,4])
m = vstack([x,y])                      # m=([[0,2,4,6,8],
                                       #     [0,1,2,3,4]])
xy = hstack([x,y])                     # xy =([0,2,4,6,8,0,1,2,3,4])

print("m : \n\n", m )
print("\n\n xy : \n\n", xy )

m : 

 [[0 2 4 6 8]
 [0 1 2 3 4]]


 xy : 

 [0 2 4 6 8 0 1 2 3 4]


In [230]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [237]:
a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
np.r_[np.repeat(a,3),np.tile(a,3)]
# np.tile(a,3)



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])